### ISSUE TITLE
Import problem

### ISSUE THREAD

**Issue by revskill10** [brandonchinn178/persistent-migration#48]
I tried using the code from README and in the test, and compiler keeps telling
```
‘constraints’ is not a (visible) field of constructor ‘CreateTable’
```

I think there's problem in my import. Do you know how to fix ?

**Comment by brandonchinn178** [comment]
Sorry, `master` is not equivalent to the latest on Hackage right now. I'm still working on what will become 0.1.0. Use the documentation on Hackage: https://hackage.haskell.org/package/persistent-migration-0.0.2
