### ISSUE TITLE
Using with an existing database

### ISSUE THREAD

**Issue by benperez** [brandonchinn178/persistent-migration#69]
Hey Brandon,

How would you recommend using this project with an existing database? I currently use persistent and just auto-apply safe migrations using the [provided persistent function](https://www.stackage.org/haddock/lts-11.10/persistent-2.8.2/Database-Persist-Sql.html#v:runMigration).

If I already have models should I just create a migration that has a `CreateTable` expression for each one? I'm guessing subsequent changes to models need hand-written migrations as well to make the database compatible with the model definitions.

**Comment by brandonchinn178** [comment]
Yes, that's exactly what you should do. CreateTable for everything now, then handwritten for subsequent changes. This allows you, as the developer, to have better control over the migrations run on the server.

Hope you're doing well, Ben!

**Comment by benperez** [comment]
Great, thanks. I got it working with my existing db. Nice job on this package btw!
