### ISSUE TITLE
Repeated inserts of the same migration

### ISSUE THREAD

**Issue by ProofOfKeags** [brandonchinn178/persistent-migration#70]
While the migrations themselves are only run once, it seems that the runMigration function indiscriminately saves the migration to the database _regardless of whether it was run_. This seems to be a bug to me.

I believe the fix to be the following (replacing the existing implementation of 'runMigration'):
```haskell
-- | Run the given migration. After successful completion, saves the migration to the database.
runMigration :: MonadIO m => MigrateBackend -> MigrateSettings -> Migration -> SqlPersistT m ()
runMigration backend settings@MigrateSettings{..} migration = do
  currVersion <- maybe (-1) id <$> getCurrVersion
  let latestVersion = getLatestVersion migration
  when (currVersion < latestVersion) $ do
    getMigration backend settings migration >>= mapM_ executeSql
    now <- liftIO getCurrentTime
    rawExecute "INSERT INTO persistent_migration(latestVersion, label, timestamp) VALUES (?, ?, ?)"
      [ PersistInt64 $ fromIntegral version
      , PersistText $ Text.pack $ fromMaybe (show version) $ versionToLabel version
      , PersistUTCTime now
      ]
```

Does this seem like an acceptable fix?

**Comment by brandon-leapyear** [comment]
:sparkles: _**This is an old work account. Please reference @brandonchinn178 for all future communication**_ :sparkles:


---

Yeah, that seems reasonable. I'm not actively maintaining this project since my company integrated the code into our codebase, but feel free to open a PR!

**Comment by tim2CF** [comment]
@CaptJakk any progress here?

**Comment by CaptJakk** [comment]
@tim2CF I don't use the library much at this point, but I did just open #72 which should fix it, if you wanna pull down the branch and test it.

**Comment by tim2CF** [comment]
thanks 👍
