### ISSUE TITLE
Fix stuff and push to hackage

### ISSUE THREAD

**Issue by tfc** [brandonchinn178/persistent-migration#76]
Hi,

i have some haskell projects which need to patch the source manually to the latest commit hash of this repo instead of just referring cabal to the hackage version of this library.
If hackage contained the latest commit this would be a reliever.

Is there anything that needs to be done before the hackage entry can get an update? Anything where i can help?

**Comment by brandonchinn178** [comment]
Sure thing; I'll push up a release today

**Comment by brandonchinn178** [comment]
https://github.com/brandonchinn178/persistent-migration/pull/77

**Comment by brandonchinn178** [comment]
http://hackage.haskell.org/package/persistent-migration-0.2.0

**Comment by tfc** [comment]
That was fast. Thank you so much!
